USE teamdimler;

ALTER TABLE productos
    ADD COLUMN IF NOT EXISTS medida VARCHAR(120) NULL AFTER descripcion,
    ADD COLUMN IF NOT EXISTS color VARCHAR(100) NULL AFTER medida,
    ADD COLUMN IF NOT EXISTS material VARCHAR(160) NULL AFTER color,
    ADD COLUMN IF NOT EXISTS stock INT UNSIGNED NULL DEFAULT NULL AFTER material,
    ADD COLUMN IF NOT EXISTS disponible TINYINT(1) NOT NULL DEFAULT 1 AFTER stock;
